version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    profiles: [web, integration]
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./src/seeds/seed_companies.sql:/docker-entrypoint-initdb.d/seed_companies.sql
      - ./src/seeds/seed_employees.sql:/docker-entrypoint-initdb.d/seed_employees.sql

  redis:
    image: redis:latest
    container_name: redis
    profiles: [web, integration]
    restart: always
    ports:
      - 6379:6379

  mongo:
    image : mongo:latest
    container_name: mongo
    profiles: [web, metadata, integration]
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - ./src/seeds/seed_employeesMetadata.js:/docker-entrypoint-initdb.d/seed_employeesMetadata.js

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    profiles: [integration]
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  metadata-app:
    build:
      dockerfile: Dockerfile
    container_name: metadata
    profiles: [integration]
    restart: on-failure
    environment:
      DEPLOY_ENV: dev
      APP: metadata/server.js
      RABBIT_URL: amqp://rabbit:5672
      MONGO_URL: mongodb://mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.4
    ports:
      - 8001:8001
    depends_on:
      - mongo
      - rabbit

  web-app:
    build:
      dockerfile: Dockerfile
    container_name: web
    profiles: [integration]
    restart: on-failure
    environment:
      DEPLOY_ENV: dev
      APP: web/server.js
      REDIS_URL: redis://redis:6379
      RABBIT_URL: amqp://rabbit:5672
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      MONGO_URL: mongodb://mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.4
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
      - mongo
      - rabbit

networks:
  default:
    name: hierarchy
