version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    profiles: ['web', 'integration']
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./src/seeds/seed_companies.sql:/docker-entrypoint-initdb.d/seed_companies.sql
      - ./src/seeds/seed_employees.sql:/docker-entrypoint-initdb.d/seed_employees.sql

  redis:
    image: redis:latest
    container_name: redis
    profiles: ['web', 'integration']
    restart: always
    ports:
      - 6379:6379

  mongo:
    image : mongo:latest
    container_name: mongo
    profiles: ['web', 'metadata', 'integration']
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - ./src/seeds/seed_employeesMetadata.js:/docker-entrypoint-initdb.d/seed_employeesMetadata.js

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    profiles: ['integration']
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  metadata-app:
    build:
      dockerfile: Dockerfile
    container_name: metadata
    profiles: ['integration']
    environment:
      RABBIT_URL: amqp://rabbit:5672
      MONGO_URL: mongodb://mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.5.4
    ports:
      - 8001:8001
    depends_on:
      - mongo
      - rabbit

networks:
  default:
    name: hierarchy
