from node:18
workdir /app
copy package*.json .
run npm i
copy . .
run npm run build
run chmod +x src/scripts/wait-for-it.sh
entrypoint src/scripts/wait-for-it.sh rabbit:5672 --strict --timeout=300 -- node dist/apps/metadata/server.js
