version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: npm i
      - run: echo
              DB_HOST=localhost$'\n'
              DB_PORT=5432$'\n'
              POSTGRES_DB=company_hierarchy_service_ts_test$'\n'
              POSTGRES_USER=me$'\n'
              POSTGRES_PASSWORD=password$'\n'
            > .env
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: docker-compose up -d
      - run: npm test

workflows:
  test_and_deploy:
    jobs:
      - test

      - heroku/deploy-via-git:
          filters:
            branches:
              only: main
          requires:
            - test
          # post-steps:
          #   - run: your-database-migration-command
          pre-steps:
            - run: npm i

  # scheduled-automation:
  #   triggers:
  #     - schedule:
  #         cron: "0 20 * * *"
  #         filters: *staging_filters
  #   jobs:
  #     - run_cypress:
  #         env: demo
  #         url: http://demo.affogata.net
  #         ignore_tests: ",ignoreTestFiles=*.only_local.spec.js"
  #         context: staging
